### PR TITLE
branch2-filexxx

### PR DESCRIPTION
**Pull request by rawat-nitin**

### CODE REVIEW

**Comment by BlackSmith09** [comment]
What is this? Explain.
image

**Review by BlackSmith09 — CHANGES_REQUESTED** [review]
I cannot understand what you have written?

**Review by BlackSmith09 — APPROVED** [review]

**Review by rawat-nitin — COMMENTED** [review]
Once again what have you written?

**Comment by rawat-nitin** [comment]
It is hex code

**Review by BlackSmith09 — APPROVED** [review]
it is okay you can merge.

**Pull request merged**
